version: '3.3'
services:
  redis:
    container_name: lfg_redis
    image: redis
    command: redis-server
    networks:
      - lfg

  database:
    container_name: lfg_db
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - lfg

  application:
    container_name: lfg_app
    build:
      context: ./django/
    restart: always
    working_dir: /app
    command: sh ./docker/wait_db.sh && sh ./docker/entrypoint.sh
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./django/:/app
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    networks:
      - lfg

volumes:
  database_data:

networks:
  lfg:
    name: lfg
