# Generated by Django 4.0.3 on 2023-08-31 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanform',
            options={'verbose_name': 'Loan Form', 'verbose_name_plural': 'Loan Forms'},
        ),
    ]
