# Generated by Django 4.0.3 on 2023-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loanform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanform',
            name='descritpion',
            field=models.TextField(blank=True, null=True, verbose_name='Decription'),
        ),
    ]
