# Generated by Django 4.0.3 on 2023-08-31 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='raw_value',
        ),
    ]
